version: "3.8"

services:
  zmonitor:
    container_name: zmonitor-dev
    image: ghcr.io/vivekjaiswar/zmonitor:latest
    volumes:
      #- ./data:/app/data
      - ../server:/app/server
      - ../db:/app/db
    ports:
      - "3001:3001" # <Host Port>:<Container Port>
      - "3307:3306"
